### ISSUE TITLE
[config]: multiple urls for same host

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/dashlord-actions#136]
Il serait utile de demander d'examiner plusieurs pages pour une url donnée

Ex : `/, /profile, /login`...

**Comment by tristanrobert** [comment]
Cela concernerait quels scans?

**Comment by tristanrobert** [comment]
OWASP regarde déjà les pages d'un domaine donné, idem 404. stats cela n'aurait pas de sens.

**Comment by revolunet** [comment]
Oui ca concerne surtout lighthouse en fait.
