### ISSUE TITLE
Remove ambiguity on Accessibility colonnes 

### ISSUE THREAD

**Issue by astranchet** [SocialGouv/dashlord-actions#288]
Les utilisateurs pensent que "100 %" en accessibilité est une bonne nouvelle. Hors, il s'agit uniquement de tests automatiques.
Je propose d'utiliser un affichage comme celui des trackers. Par exemple : 
- ✅ pour 100 % aux tests automatiques
- Si des erreurs, le nombre d'erreurs en rouge

Et renommer la colonne en "Tests automatiques d'accessibilité"

![Capture d’écran 2023-12-05 à 09 31 40](https://github.com/SocialGouv/dashlord-actions/assets/1374389/97533467-1b67-4526-986e-d5c583a404b6)

**Comment by revolunet** [comment]
Alors actuellement je n'ai pas le "nombre d'erreurs" d'accessibilité détectées dans les données, seulement un score de 0 à 1 qui est convertit en % à l'affichage.

<img width="76" alt="Capture d’écran 2023-12-10 à 23 05 10" src="https://github.com/SocialGouv/dashlord-actions/assets/124937/3e4efff3-daf4-422c-a664-1d518b5b7180">

D'autres idées ?

**Comment by astranchet** [comment]
Aïe, en console, j'avais l'impression que le nombre d'erreur était proposé aussi : https://github.com/GoogleChrome/lighthouse-ci

Pour les couleurs, on peut toujours améliorer : 
- [ ] Vert uniquement pour le 100 %
- [ ] Orange pour 90 à 99 %
- [ ] Rouge en dessous

Pour le texte, je pense qu'il faut vraiment s'écarter du pourcentage. À défaut du nombre d'erreurs, on pourrait alors avoir : 
- une lettre (A, B, C...) ? mais les gens ont toujours des questions sur le sens de la lettre, et là ça serait une correspondance totalement inventée
- le chiffre en décimal (0,99/1) : avec un peu de chance, ça ferait moins penser au score RGAA ? et on ne perd pas l'info ?
- afficher le drapeau ⚠️ si il y a une erreur, et la checkbox si 100 %
Je crois que je préfère cette dernière solution. Ça te paraît bien ?

**Comment by revolunet** [comment]
Nouvelle proposition

<img width="107" alt="Capture d’écran 2023-12-14 à 11 11 11" src="https://github.com/SocialGouv/dashlord-actions/assets/124937/8240d27e-2117-4494-b7b9-9efd3943ae06">

Avec cet algo pour définir la lettre affichée : 

```js
 if (value >= 1) {
    return "✔";
  } else if (value >= 0.85) {
    return "B";
  } else if (value >= 0.7) {
    return "C";
  } else {
    return "⚠️";
  }
```

**Comment by astranchet** [comment]
Possible de mettre le B en orange plutôt que vert ? 
Sinon pourquoi pas oui. Le warning pourrait aussi être un F.

**Comment by revolunet** [comment]
Voici les règles pour l'affichage de ce score lighthouse :

Score lighthouse | Couleur | Texte
:---------------:|:-------:|:----:
100%             | success   | ✓
\>= 85%          | warning   | B
\>= 70%          | danger    | C
< 70%            | danger    | ⚠️

<img width="111" alt="Capture d’écran 2024-01-10 à 00 33 33" src="https://github.com/SocialGouv/dashlord-actions/assets/124937/0724c7d4-5bcc-4f85-bfa7-01bdadb56c57">

good ?

**Comment by astranchet** [comment]
Parfait ! Merci beaucoup !
