### ISSUE TITLE
ui: source url click do nothing

### ISSUE THREAD

**Issue by tristanrobert** [SocialGouv/dashlord-actions#59]

**Comment by tristanrobert** [comment]
Depends on: https://github.com/dataesr/react-dsfr/issues/196

**Comment by revolunet** [comment]
how to reproduce ? which component

**Comment by tristanrobert** [comment]
![Screenshot 2021-09-20 at 10-49-10 Dashlord](https://user-images.githubusercontent.com/19711088/133977247-27eee8cc-c9d2-4e41-9db6-2f0cc2c8ea7a.png)

**Comment by tristanrobert** [comment]
Lien retiré
